[package]
name = "pawnpro-core"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
encoding_rs = { workspace = true }
sysinfo = { workspace = true }
pawnpro-engine = { path = "../engine" }
pawnpro-dap-adapter = { path = "../debugger/adapter" }
tokio = { workspace = true, features = ["rt-multi-thread", "net", "time", "io-util"] }
tokio-util = { workspace = true, features = ["io-util"] }

[dev-dependencies]
pawnpro-dbg-protocol = { path = "../debugger/protocol" }
tokio = { workspace = true, features = ["macros", "test-util"] }
